[profiles.default]
flake = "flake.nix#default"

[profiles.services]
flake = "flake.nix#services"

[environment]
pass = ["CHROME_EXECUTABLE", "CI", "DBUS_SESSION_BUS_ADDRESS", "E2E_TIMEOUT_SECONDS", "GITHUB_TOKEN", "LANG", "LC_ALL"]

[profiles.formatter]
flake = "flake.nix#formatter"
entry_setup = []
